### PR TITLE
Improve build badge

### PR DESCRIPTION
**Pull request by tetchel**

### CODE REVIEW

**Comment by tetchel** [comment]
> protected exposes the badge to users having at least Read permission on the job

Everyone has read permission on our jenkins jobs. I can view the badge fine in an incognito session

**Comment by tetchel** [comment]
I suppose both should work the same since our permissions are open

**Comment by josephca** [comment]
> I suppose both should work the same since our read / view status permissions are both open

Right. So, let's keep them as they are. Thanks.

**Comment by tetchel** [comment]
I totally didn't realize you'd already made this change; I thought I was replacing the red icon from yesterday. Now I see what happened

**Pull request closed without merging**
