### PR TITLE
Update upload location for pull requests

### PR DESCRIPTION
**Pull request by mmulholl**
Signed-off-by: Martin Mulholland <mmulholl@us.ibm.com>

### CODE REVIEW

**Comment by tetchel** [comment]
why upload at all for PRs?

**Comment by tetchel** [comment]
I would rather not upload at all given that we have seen the deploy step get stuck for hours, which would result in being unable to merge changes for hours.

**Comment by mmulholl** [comment]
@tetchel we upload pr's so that the owner/reviewer of the PR can download and test the resuls

**Comment by tetchel** [comment]
okay, forget about my other concern i guess...

**Comment by tetchel** [comment]
if they want to test it they can fetch and check it out themselves

**Pull request merged**
